/* AUTO-GENERATED by build-gate-from-coverage.cjs — DO NOT EDIT MANUALLY */
const buckets = {
  withdrawals: [/umbral-minimo/i, /umbral/i, /umbral minimo/i, /safety net/i, /mínimo para retirar/i, /payout threshold/i, /payouts-frecuencia/i, /payouts/i, /retiro/i, /withdrawal frequency/i, /profit split/i, /minimo retiro/i, /payouts-requisitos/i, /requisitos retiro/i, /dias minimos/i, /consistencia 30%/i, /limits-retiro/i, /limite retiro/i, /maximo retiro/i, /primeros 5 retiros/i],
  pricing: [/cuotas-activacion/i, /activacion/i, /activation fee/i, /cuota de activacion/i, /pago unico/i, /suscripcion mensual/i, /reset-evaluacion/i, /reset/i, /reinicio/i, /restart/i, /pago inmediato/i, /renovacion/i, /planes-disponibles/i, /tamanos/i, /precios/i, /planes/i, /1-step/i, /static/i],
  payment_methods: [/metodos-de-pago/i, /metodos de pago/i, /formas de pago/i, /payment methods/i, /tarjeta/i, /paypal/i, /crypto/i, /transferencia/i, /wise/i, /plane/i],
  rules: [/drawdown-tipos/i, /trailing drawdown/i, /static drawdown/i, /congelacion drawdown/i, /evaluacion-objetivo-minimos/i, /profit target/i, /dias minimos/i, /tiempo limite/i, /overnight-news/i, /overnight/i, /swing/i, /news/i, /one-direction/i, /horario-sesion/i, /horario/i, /sesion/i, /6pm et a 4:59pm et/i, /escalado-contratos/i, /contratos maximos/i, /escalado/i, /porcentaje 50%/i, /micros/i, /regla-30-negativo/i, /30% pnl negativo/i, /perdidas abiertas 30%/i, /safety net 30%/i, /gestion-riesgo/i, /5:1/i, /stops/i, /no usar todo drawdown/i, /comisiones/i, /fees/i, /rithmic/i, /tradovate/i, /round trip/i, /comisiones/i, /pagos-requisitos-auditoria/i, /auditoria/i, /zoom/i, /logs 30 dias/i, /probation/i, /copy trading prohibido/i, /automatizacion/i],
  platforms: [/plataformas-disponibles/i, /plataformas/i, /ninjatrader/i, /tradovate/i, /rithmic/i, /wealthcharts/i, /tradingview/i],
  discounts: []
};

const order = ["withdrawals","pricing","payment_methods","rules","platforms","discounts"];

function gateIntent(query) {
  const q = String(query || '').toLowerCase();
  const hits = order.filter(k => buckets[k].some(r => r.test(q)));
  return hits.length ? hits : order;
}

module.exports = { gateIntent };
